# Generated by Django 4.1.2 on 2022-11-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_checkoutproducts_qty_checkoutproducts_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutproducts',
            name='total',
            field=models.IntegerField(default=1),
        ),
    ]
